# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField()),
                ('idAnim', models.IntegerField(null=True)),
                ('nameAnim', models.CharField(max_length=300, null=True)),
                ('valence', models.FloatField(null=True)),
                ('arousal', models.FloatField(null=True)),
                ('numPlay', models.IntegerField(null=True)),
                ('startAnimTime', models.FloatField(null=True)),
                ('endAnimTime', models.FloatField(null=True)),
                ('order', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
