# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0002_judge_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='trial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
