# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0003_judge_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='arousal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='endAnimTime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='idAnim',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='nameAnim',
            field=models.CharField(default='ok', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='numPlay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='order',
            field=models.CharField(default='V', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='startAnimTime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judge',
            name='valence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
