# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0004_auto_20170503_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='sex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
