# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0005_auto_20170522_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='judge',
            name='age',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='group',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='sex',
        ),
    ]
