# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0006_auto_20170523_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='diff',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
