# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0007_judge_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='naf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographic',
            name='paf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
