# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalemo', '0008_auto_20170529_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='diff',
            new_name='diff_a',
        ),
        migrations.AddField(
            model_name='judge',
            name='diff_v',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
